SET CHARSET UTF8;

CREATE TABLE IF NOT EXISTS users
(
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  name TEXT NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS article
(
  id MEDIUMINT NOT NULL,
  title MEDIUMTEXT NOT NULL,
  detail LONGTEXT,
  type TEXT,
  img_url TEXT,
  created_at DATETIME,
  updated_at DATETIME,
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS comment
(
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  user_id MEDIUMINT NOT NULL,
  article_id MEDIUMINT NOT NULL,
  detail LONGTEXT,
  PRIMARY KEY(id)
); 
