- hosts: webapp
  user: ec2-user
  gather_facts: yes

  roles:
    # - bootstrap
    # - nginx
    # - mariadb
    # - python
    # - nodejs
    # - webapp.deploy
    # - webapp.mariadb
    # - webapp.python
    # - webapp.nodejs
    - webapp.nginx

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      with_items:
        - nginx.service
        - mariadb.service
        - flask.service
